<?xml version="1.0"?>
<package format="3">
  <name>gazebo_pose_tools</name>
  <version>0.0.1</version>
  <description>ROS 2 service for getting pose of objects in Gazebo Sim</description>
  <maintainer email="dawid.seredynski@gmail.com">Dawid Seredyński</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>builtin_interfaces</depend>
  <depend>gazebo_pose_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
